# Generated by Django 5.1 on 2024-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botgroup',
            old_name='grp_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='botgroup',
            name='grp_url',
        ),
        migrations.AddField(
            model_name='botgroup',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='botgroup',
            name='platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='Facebook', max_length=50),
        ),
        migrations.AddField(
            model_name='botgroup',
            name='url',
            field=models.URLField(default='https://www.example.com'),
            preserve_default=False,
        ),
    ]
