# Generated by Django 5.1 on 2024-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_rename_grp_title_botgroup_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_platform',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='Facebook', max_length=50),
        ),
        migrations.AlterField(
            model_name='bot',
            name='send_opt',
            field=models.CharField(choices=[('all_days', 'All Days'), ('selected_days', 'Selected Days'), ('day', 'One Day per Week')], default='all_days', max_length=50),
        ),
    ]
